### ISSUE TITLE
Refactor Post database Save function

### ISSUE THREAD

**Issue by icco** [icco/graphql#7]
There are currently two Post database functions for saving:

 - CreatePost https://godoc.org/github.com/icco/graphql#CreatePost
 - Save https://godoc.org/github.com/icco/graphql#Post.Save

Only Save needs to exist. Move the logic from CreatePost into Save and then change the save query to be an UPSERT instead of an INSERT.

**Comment by 1uka** [comment]
taking this up, should be quick
