### ISSUE TITLE
Make error pages consistent

### ISSUE THREAD

**Issue by icco** [icco/graphql#9]
There is a nice 404 error page: https://graphql.natwelch.com/404

It's rendered by https://github.com/icco/graphql/blob/master/server/server.go#L175-L177 and https://github.com/icco/graphql/blob/master/server/views/404.tmpl.

I would like for the server to respond with a page that acts like this for all http errors.

**Comment by michaelsanford** [comment]
Getting my feet wet in Go; I'd like to take a stab at this.

**Comment by icco** [comment]
Sure!

**Comment by icco** [comment]
This has been done.
